version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: location
      POSTGRES_USER: location
      POSTGRES_PASSWORD: location
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U location"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI

  server:
    image: location-server:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/location
      DB_USER: location
      DB_PASS: location
      JWT_SECRET: changeme-please
    ports:
      - "8080:8080"

volumes:
  dbdata:
