ALTER TABLE client ADD COLUMN IF NOT EXISTS billing_address VARCHAR(200);
ALTER TABLE client ADD COLUMN IF NOT EXISTS billing_zip VARCHAR(16);
ALTER TABLE client ADD COLUMN IF NOT EXISTS billing_city VARCHAR(120);
ALTER TABLE client ADD COLUMN IF NOT EXISTS vat_number VARCHAR(32);
ALTER TABLE client ADD COLUMN IF NOT EXISTS iban VARCHAR(34);
