server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,application/pdf
    min-response-size: 1024

spring:
  application:
    name: location-server
  main:
    banner-mode: "off"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging.level.org.springframework.security: INFO
