spring:
  datasource:
    url: jdbc:h2:mem:location;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-please-change-dev-secret}
