name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build & Test
        run: mvn -B -ntp verify
      - name: Checkstyle
        run: mvn -B -ntp -DskipTests checkstyle:check
      - name: PMD
        run: mvn -B -ntp -DskipTests pmd:check

  docker-server:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Build server image
        run: docker build -t location-server:ci ./server
      - name: Save image artifact
        run: |
          docker save location-server:ci | gzip > server-image.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: server-image
          path: server-image.tar.gz
